### PR TITLE
Create model assumptions

### PR DESCRIPTION
**Pull request by bodzaruz**
I have written the introduction and defined the model assumptions on which I intend to base the simulations.
Requesting approval.

### CODE REVIEW

**Comment by mykola2004** [comment]
- **The task motivation and introduction** to the problem including historical elements is teriffic -- OK

Assumptions:
- **Size of tribe** -- OK
- **Human Age** -- OK
BUT: What are initial tribe members ages at the start of simulations? I suggest to set all as 0 (which is unrealistic, should be take as an assumption; OR you can pick up some other constant value , like 20 y.o ., etc).
- **Marriage** -- OK
BUT: was not mentioned anything about probability with which a pair would be created from siblings.
- **Offspring**
a) I do not understand your idea: "Each pair has the chance to have offspring during the period T_0."

T_0 - maximum age when men and women are able to reproduce. Have you meant that?
Let us consider an example, such a pair was created: female(with age 20) and man(with age 35). For this example T_0 = 40. Than time during which they are able to reproduce is next 5 years. 
So, correctly would be to state: 
_Each pair has the chance to have offspring during the period min { T_0 - age_start_wife; T_0 - age_start_husband}._ 

b)  The number of offspring is determined by a Poisson distribution with parameter lambda. The parameter lambda is determined by the user -- OK, the distribution is chosen correctly. 

c) Was written: "The moment of birth is random with uniform distribution...".
That is not correct. First of all, should be introduced parameter time_childbearing(could be adjusted before simulations by user), which would flag how much time is needed for a woman to bear a child(children) at once (for example, in reality for humans time_childbearing = 9 MONTHS). 

Knowing that between different birth dates should pass time >= to value of parameter time_childbearing.

-  **Inbred** 
a) -- OK
BUT:
was written: "up to third generation" that could be substituted with: "up to G generation", where G - is parameter of simulations, with possible values from set of N(naturalnumbers).

b) -- OK; sounds to be reasonable

- **Time of simulation** -- OK
- **We observe** -- OK

**Comment by bodzaruz** [comment]
> * **The task motivation and introduction** to the problem including historical elements is teriffic -- OK
> 
> 
> Assumptions:
> 
>     * **Size of tribe** -- OK
> 
>     * **Human Age** -- OK
>       BUT: What are initial tribe members ages at the start of simulations? I suggest to set all as 0 (which is unrealistic, should be take as an assumption; OR you can pick up some other constant value , like 20 y.o ., etc).
> 
>     * **Marriage** -- OK
>       BUT: was not mentioned anything about probability with which a pair would be created from siblings.
> 
>     * **Offspring**
>       a) I do not understand your idea: "Each pair has the chance to have offspring during the period T_0."
> 
> 
> T_0 - maximum age when men and women are able to reproduce. Have you meant that? Let us consider an example, such a pair was created: female(with age 20) and man(with age 35). For this example T_0 = 40. Than time during which they are able to reproduce is next 5 years. So, correctly would be to state: _Each pair has the chance to have offspring during the period min { T_0 - age_start_wife; T_0 - age_start_husband}._
> 
> b) The number of offspring is determined by a Poisson distribution with parameter lambda. The parameter lambda is determined by the user -- OK, the distribution is chosen correctly.
> 
> c) Was written: "The moment of birth is random with uniform distribution...". That is not correct. First of all, should be introduced parameter time_childbearing(could be adjusted before simulations by user), which would flag how much time is needed for a woman to bear a child(children) at once (for example, in reality for humans time_childbearing = 9 MONTHS).
> 
> Knowing that between different birth dates should pass time >= to value of parameter time_childbearing.
> 
>     * **Inbred**
>       a) -- OK
>       BUT:
>       was written: "up to third generation" that could be substituted with: "up to G generation", where G - is parameter of simulations, with possible values from set of N(naturalnumbers).
> 
> 
> b) -- OK; sounds to be reasonable
> 
>     * **Time of simulation** -- OK
> 
>     * **We observe** -- OK

Ad. Human Age. 
Valid point and interesting suggestion. I have expanded assumption in 'Size of tribe'.

Ad. Marriage.
I assumed that the formation of marriage pairs is random. This means that there is a non-zero probability of forming a pair by siblings, cousins, etc.

Ad. Offspring.
Indeed, the introduced time constant $T_0$ caused some confusion. I made the appropriate corrections by adding point 'Reproductive age'. I also added the condition of a minimum interval between consecutive births in subpoint 'Birth'.

Ad. Inbred.
I took into account the suggestion to make the degree of kinship more flexible. I introduced an additional parameter.

**Comment by mykola2004** [comment]
- **Marriage**. okay, i get it, let's leave it how it was at the beginning, my fault.
please add discussed before corrections to the assumtions of the model

**Comment by bodzaruz** [comment]
If you consider the assumptions to be correct, please merge the pull request. 
I will create a new branch for the next project step.

**Pull request merged**
